"""teams seeded with data

Revision ID: 02a2b71ed588
Revises: c80d32ce23dc
Create Date: 2023-06-09 02:46:17.731843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a2b71ed588'
down_revision = 'c80d32ce23dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
