"""coaches seeded with data

Revision ID: 387605864686
Revises: 02a2b71ed588
Create Date: 2023-06-09 02:49:36.789748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387605864686'
down_revision = '02a2b71ed588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
