"""players and playerstats successfully seeded with data

Revision ID: a4a9f00b2280
Revises: 387605864686
Create Date: 2023-06-09 02:55:03.981637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a9f00b2280'
down_revision = '387605864686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
