"""models

Revision ID: c80d32ce23dc
Revises: fb82565ca974
Create Date: 2023-06-09 02:36:46.592633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c80d32ce23dc'
down_revision = 'fb82565ca974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
